import type { ProtocolDefinition, Scenario, Step } from "../../domain/lesson";
import { createConnection } from "../tcp";

const tls = "https://www.rfc-editor.org/rfc/rfc8446#section-";
const http = "https://www.rfc-editor.org/rfc/rfc9110#section-";
const http1 = "https://www.rfc-editor.org/rfc/rfc9112#section-";

function message(
  id: string,
  phase: string,
  title: string,
  wire: string,
  from: "client" | "server",
  to: "client" | "server",
  description: string,
  fields: string[],
  protection: string,
  source: string,
): Step {
  return {
    kind: "message",
    id,
    phase,
    title,
    wire,
    from,
    to,
    description,
    fields,
    protection,
    source,
  };
}

const scenario = {
  id: "tls13-http11",
  title: "HTTPSでWebページを取得する",
  badge: "HTTPS · TLS 1.3",
  sceneLabel: "browser ↔ web server",
  nodes: [
    {
      id: "client",
      label: "BROWSER",
      caption: "ブラウザー",
      image: "./pixels/client.svg",
    },
    {
      id: "server",
      label: "WEB SERVER",
      caption: "Webサーバー",
      image: "./pixels/server.svg",
    },
  ],
  prerequisites: [{ protocol: "tcp", label: "TCP接続の確立" }],
  notes: [
    "この教材では、TLS 1.3のフルハンドシェイク後にHTTP/1.1を送ります。HTTPSはTLSでHTTPを保護します。使うHTTPのバージョンや接続方式は、状況によって異なります。",
    "TCP接続後にTLSを始める、一般的な構成です。説明を絞るため、DNS、TLSセッション再開、0-RTT、HelloRetryRequest、クライアント証明書、HTTP/2・HTTP/3、複数の要求、切断は省略します。",
    "ClientHelloとServerHelloは、暗号化せずに送ります。その後のハンドシェイクメッセージとHTTPデータはTLSで保護します。ただし、通信相手、データ量、通信のタイミングなどは、すべて隠れるわけではありません。",
    "サーバー証明書を受け取るだけでは、認証は完了しません。証明書チェーンと接続先のホスト名を検証する必要があります。この教材では、検証に成功する場合だけを示します。",
  ],
  steps: [
    ...createConnection({ phase: "TCP接続" }),
    message(
      "client-hello",
      "TLSハンドシェイク",
      "TLS 1.3の条件を提示する",
      "ClientHello",
      "client",
      "server",
      "ブラウザーは、使えるTLSのバージョン、暗号方式、鍵共有情報を示します。接続先名（SNI）や、HTTP/1.1を使うことを示すALPN情報も含めることがあります。",
      [
        "supported_versions: TLS 1.3",
        "key_share",
        "server_name: example.com",
        "ALPN: http/1.1",
      ],
      "暗号化前",
      tls + "4.1.2",
    ),
    message(
      "server-hello",
      "TLSハンドシェイク",
      "TLSの方式と鍵共有を選ぶ",
      "ServerHello",
      "server",
      "client",
      "サーバーは、TLS 1.3で使う暗号方式と鍵共有情報を選びます。ブラウザーとサーバーは、共有した鍵素材からハンドシェイク用の鍵を作ります。この後のTLSハンドシェイクは、その鍵で保護します。",
      ["選択したTLS 1.3暗号方式", "key_share"],
      "暗号化前",
      tls + "4.1.3",
    ),
    message(
      "encrypted-extensions",
      "TLSハンドシェイク",
      "暗号化された接続条件を返す",
      "EncryptedExtensions",
      "server",
      "client",
      "サーバーは、ClientHelloで示された条件への応答を返します。選んだALPNなどが含まれます。このメッセージは、ハンドシェイク用の鍵で暗号化されています。",
      ["選択されたALPN: http/1.1"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.3.1",
    ),
    message(
      "certificate",
      "TLSハンドシェイク",
      "サーバー証明書を提示する",
      "Certificate",
      "server",
      "client",
      "サーバーは、接続先名に対応する証明書と中間証明書を送ります。ブラウザーが証明書を受け取っただけでは、サーバーの認証は完了しません。",
      ["サーバー証明書チェーン", "対象名: example.com"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.2",
    ),
    message(
      "certificate-verify",
      "TLSハンドシェイク",
      "秘密鍵を持つことを証明する",
      "CertificateVerify",
      "server",
      "client",
      "サーバーは、ハンドシェイクの内容に署名します。証明書に対応する秘密鍵を持っていることを、この署名で証明します。",
      ["ハンドシェイク内容への署名"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.3",
    ),
    message(
      "server-finished",
      "TLSハンドシェイク",
      "サーバー側のハンドシェイクを完了する",
      "Finished",
      "server",
      "client",
      "サーバーは、ここまでのハンドシェイクを検証する値を送ります。これでサーバー側のハンドシェイクは完了です。",
      ["transcript hashに対する検証値"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.4",
    ),
    {
      kind: "local",
      id: "verify-server",
      phase: "TLSハンドシェイク",
      title: "証明書と署名を検証する",
      wire: "証明書の検証に成功",
      node: "client",
      effect: {
        kind: "stages",
        stages: [
          { text: "証明書チェーンを確認", status: "信頼できる発行元か" },
          {
            text: "接続先名と証明書の用途を確認",
            status: "対象サーバーと一致するか",
          },
          { text: "CertificateVerify署名を確認", status: "秘密鍵の所持を確認" },
        ],
        label: "サーバー証明書の検証",
      },
      description:
        "ブラウザーは、証明書チェーンと接続先のホスト名を確認します。CertificateVerifyの署名も検証します。どれかに失敗するとHTTPS通信を中止します。この教材では、すべて成功する場合を示します。",
      fields: [
        "証明書の信頼チェーン",
        "接続先ホスト名",
        "CertificateVerify署名",
      ],
      protection: "端末内の検証",
      source: http + "4.3.4",
    },
    message(
      "client-finished",
      "TLSハンドシェイク",
      "クライアント側のハンドシェイクを完了する",
      "Finished",
      "client",
      "server",
      "ブラウザーも、ここまでのハンドシェイクを検証する値を送ります。これでTLS接続が確立し、双方がアプリケーションデータ用の鍵を使えるようになります。",
      ["transcript hashに対する検証値"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.4",
    ),
    message(
      "http-request",
      "HTTP通信",
      "HTTPSでHTTP要求を送る",
      "TLS Application Data · GET /index.html",
      "client",
      "server",
      "ブラウザーは、確立したTLS接続を通してHTTP/1.1の要求を送ります。ネットワーク上ではTLSのアプリケーションデータに見え、HTTPの内容は暗号化されています。",
      ["GET /index.html HTTP/1.1", "Host: example.com"],
      "TLSアプリケーション鍵で暗号化・改ざん検知",
      http1 + "3.1",
    ),
    message(
      "http-response",
      "HTTP通信",
      "暗号化されたHTTP応答を受け取る",
      "TLS Application Data · 200 OK",
      "server",
      "client",
      "サーバーは、TLSで保護したHTTP応答を返します。ブラウザーは応答を復号して改ざんがないか検証し、その後にHTTP応答として処理します。",
      ["HTTP/1.1 200 OK", "Content-Type: text/html", "応答本文"],
      "TLSアプリケーション鍵で暗号化・改ざん検知",
      http1 + "4",
    ),
  ],
} satisfies Scenario;

export const https: ProtocolDefinition = {
  id: "https",
  title: "HTTPS",
  description: "TLSで通信を保護し、Webサーバーを認証してHTTPを送受信する",
  keywords: ["Web", "TLS", "暗号化", "証明書", "HTTP", "SSL", "ウェブページ"],
  defaultScenarioId: scenario.id,
  scenarios: [scenario],
};
