import type { ProtocolDefinition, Scenario, Step } from "../../domain/lesson";
import { createConnection } from "../tcp";

const tls = "https://www.rfc-editor.org/rfc/rfc8446#section-";
const http = "https://www.rfc-editor.org/rfc/rfc9110#section-";
const http1 = "https://www.rfc-editor.org/rfc/rfc9112#section-";

function message(
  id: string,
  phase: string,
  title: string,
  wire: string,
  from: "client" | "server",
  to: "client" | "server",
  description: string,
  fields: string[],
  protection: string,
  source: string,
): Step {
  return {
    kind: "message",
    id,
    phase,
    title,
    wire,
    from,
    to,
    description,
    fields,
    protection,
    source,
  };
}

const scenario = {
  id: "tls13-http11",
  title: "HTTPSでWebページを取得する",
  badge: "HTTPS · TLS 1.3",
  sceneLabel: "browser ↔ web server",
  nodes: [
    {
      id: "client",
      label: "BROWSER",
      caption: "ブラウザー",
      image: "./pixels/client.svg",
    },
    {
      id: "server",
      label: "WEB SERVER",
      caption: "Webサーバー",
      image: "./pixels/server.svg",
    },
  ],
  prerequisites: [{ protocol: "tcp", label: "TCP接続の確立" }],
  notes: [
    "TLS 1.3のフルハンドシェイクでHTTP/1.1を運ぶ一例です。HTTPSはHTTPをTLSで保護して運びます。具体的なHTTPバージョンや下位の接続方式は状況により異なります。",
    "説明を絞るため、DNS、TLSセッション再開・0-RTT、HelloRetryRequest、クライアント証明書、HTTP/2・HTTP/3、複数要求、切断は省略しています。TCP接続後にTLSを始める通常の構成を示します。",
    "TLS 1.3ではClientHelloとServerHelloは暗号化前に送られます。ServerHello後のハンドシェイクメッセージとHTTPデータはTLSで保護されますが、通信相手・サイズ・タイミングなどの情報まで全て隠れるわけではありません。",
    "サーバー証明書は証明書チェーンと接続先ホスト名を検証して初めて認証に使えます。この例では検証に成功する場合だけ続行し、失敗時の中断は別表示にしていません。",
  ],
  steps: [
    ...createConnection({ phase: "TCP接続" }),
    message(
      "client-hello",
      "TLSハンドシェイク",
      "TLS 1.3の条件を提示する",
      "ClientHello",
      "client",
      "server",
      "ブラウザーが対応するTLSバージョンや暗号方式、鍵共有情報を提示します。接続先名（SNI）やHTTP/1.1を使うというALPN情報を含めることがあります。",
      [
        "supported_versions: TLS 1.3",
        "key_share",
        "server_name: example.com",
        "ALPN: http/1.1",
      ],
      "暗号化前",
      tls + "4.1.2",
    ),
    message(
      "server-hello",
      "TLSハンドシェイク",
      "TLSの方式と鍵共有を選ぶ",
      "ServerHello",
      "server",
      "client",
      "サーバーがTLS 1.3と鍵共有の応答を選びます。両者は共有鍵素材からハンドシェイク用の鍵を導き、以降のTLSハンドシェイクを保護できるようになります。",
      ["選択したTLS 1.3暗号方式", "key_share"],
      "暗号化前",
      tls + "4.1.3",
    ),
    message(
      "encrypted-extensions",
      "TLSハンドシェイク",
      "暗号化された接続条件を返す",
      "EncryptedExtensions",
      "server",
      "client",
      "サーバーがClientHelloへの応答拡張を返します。選ばれたALPNなどが含まれます。このメッセージはServerHello後なので暗号化されています。",
      ["選択されたALPN: http/1.1"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.3.1",
    ),
    message(
      "certificate",
      "TLSハンドシェイク",
      "サーバー証明書を提示する",
      "Certificate",
      "server",
      "client",
      "サーバーが接続先名に対応する証明書と中間証明書の情報を送ります。証明書の提示だけでは相手の認証は完了しません。",
      ["サーバー証明書チェーン", "対象名: example.com"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.2",
    ),
    message(
      "certificate-verify",
      "TLSハンドシェイク",
      "秘密鍵を持つことを証明する",
      "CertificateVerify",
      "server",
      "client",
      "サーバーが証明書に対応する秘密鍵でハンドシェイク内容への署名を行い、秘密鍵の所持を証明します。",
      ["ハンドシェイク内容への署名"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.3",
    ),
    message(
      "server-finished",
      "TLSハンドシェイク",
      "サーバー側のハンドシェイクを完了する",
      "Finished",
      "server",
      "client",
      "サーバーがハンドシェイク全体を検証するための値を送り、サーバー側のハンドシェイクを完了します。",
      ["transcript hashに対する検証値"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.4",
    ),
    {
      kind: "local",
      id: "verify-server",
      phase: "TLSハンドシェイク",
      title: "証明書と署名を検証する",
      wire: "証明書の検証に成功",
      node: "client",
      effect: {
        kind: "stages",
        stages: [
          { text: "証明書チェーンを確認", status: "信頼できる発行元か" },
          {
            text: "接続先名と証明書の用途を確認",
            status: "対象サーバーと一致するか",
          },
          { text: "CertificateVerify署名を確認", status: "秘密鍵の所持を確認" },
        ],
        label: "サーバー証明書の検証",
      },
      description:
        "ブラウザーは証明書の信頼チェーンと接続先の識別情報を確認し、CertificateVerifyの署名も検証します。検証に失敗すればHTTPS通信を続けず、ここでは成功した場合を示します。",
      fields: [
        "証明書の信頼チェーン",
        "接続先ホスト名",
        "CertificateVerify署名",
      ],
      protection: "端末内の検証",
      source: http + "4.3.4",
    },
    message(
      "client-finished",
      "TLSハンドシェイク",
      "クライアント側のハンドシェイクを完了する",
      "Finished",
      "client",
      "server",
      "ブラウザーがハンドシェイク全体を検証する値を送り、TLS接続を確立します。双方でアプリケーションデータ用の鍵が使える状態になります。",
      ["transcript hashに対する検証値"],
      "TLSハンドシェイク鍵で暗号化",
      tls + "4.4.4",
    ),
    message(
      "http-request",
      "HTTP通信",
      "HTTPSでHTTP要求を送る",
      "TLS Application Data · GET /index.html",
      "client",
      "server",
      "TLSで確立した接続を通してHTTP/1.1要求を送ります。外側からはTLSのアプリケーションデータとして見え、HTTPの内容は暗号化されています。",
      ["GET /index.html HTTP/1.1", "Host: example.com"],
      "TLSアプリケーション鍵で暗号化・完全性保護",
      http1 + "3.1",
    ),
    message(
      "http-response",
      "HTTP通信",
      "暗号化されたHTTP応答を受け取る",
      "TLS Application Data · 200 OK",
      "server",
      "client",
      "サーバーはTLSで保護したHTTP応答を返します。ブラウザーはTLSで復号・検証してからHTTP応答として処理します。",
      ["HTTP/1.1 200 OK", "Content-Type: text/html", "応答本文"],
      "TLSアプリケーション鍵で暗号化・完全性保護",
      http1 + "4",
    ),
  ],
} satisfies Scenario;

export const https: ProtocolDefinition = {
  id: "https",
  title: "HTTPS",
  description: "TLSで通信を保護し、Webサーバーを認証してHTTPを送受信する",
  keywords: ["Web", "TLS", "暗号化", "証明書", "HTTP", "SSL", "ウェブページ"],
  defaultScenarioId: scenario.id,
  scenarios: [scenario],
};
